/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CostDonut: typeof import('./components/CostDonut.vue')['default']
    DiffView: typeof import('./components/DiffView.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HITLBlockingModal: typeof import('./components/HITLBlockingModal.vue')['default']
    HITLTray: typeof import('./components/HITLTray.vue')['default']
    MainContent: typeof import('./components/layout/MainContent.vue')['default']
    NBreathingLight: typeof import('./components/common/NBreathingLight.vue')['default']
    NButton: typeof import('./components/common/NButton.vue')['default']
    NCard: typeof import('./components/common/NCard.vue')['default']
    NModal: typeof import('./components/common/NModal.vue')['default']
    NSlider: typeof import('./components/common/NSlider.vue')['default']
    NTag: typeof import('./components/common/NTag.vue')['default']
    NToast: typeof import('./components/common/NToast.vue')['default']
    NTypewriter: typeof import('./components/common/NTypewriter.vue')['default']
    NWorkflowStepper: typeof import('./components/common/NWorkflowStepper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellBannerStack: typeof import('./components/layout/ShellBannerStack.vue')['default']
    ShellCommandPalette: typeof import('./components/layout/ShellCommandPalette.vue')['default']
    ShellPageHeader: typeof import('./components/layout/ShellPageHeader.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SkillCard: typeof import('./components/SkillDSL/SkillCard.vue')['default']
    SkillDSL: typeof import('./components/SkillDSL/index.vue')['default']
    SystemButton: typeof import('./components/system/SystemButton.vue')['default']
    SystemCard: typeof import('./components/system/SystemCard.vue')['default']
    SystemDrawer: typeof import('./components/system/SystemDrawer.vue')['default']
    SystemEmpty: typeof import('./components/system/SystemEmpty.vue')['default']
    SystemErrorState: typeof import('./components/system/SystemErrorState.vue')['default']
    SystemFormField: typeof import('./components/system/SystemFormField.vue')['default']
    SystemPageHeader: typeof import('./components/system/SystemPageHeader.vue')['default']
    SystemSection: typeof import('./components/system/SystemSection.vue')['default']
    SystemSkeleton: typeof import('./components/system/SystemSkeleton.vue')['default']
    SystemStatusBanner: typeof import('./components/system/SystemStatusBanner.vue')['default']
    SystemVisualizationFallback: typeof import('./components/system/SystemVisualizationFallback.vue')['default']
    ThemeModeDropdown: typeof import('./components/layout/ThemeModeDropdown.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
    TraceInspector: typeof import('./components/TraceInspector.vue')['default']
  }
}
